const names = [
    "Burlington Coat",
    "Butterfree Catinhat",
    "Bobcat Goldthwait!",
    "Balladry Caterwaul",
    "Buffalo Custardbath",
    "Butterfried Cobsalad",
    "Benevolent Cucumber",
    "Beenadick Upyourass",
    "Robotic Rubbersnatch",
    "Bucket Crunderdunder",
    "Buttercup Candycrush",
    "Burlington Coatfactory",
    "Bulbasaur Camouflage",
    "Benadryl Slumbercatch",
    "Britishman Fancyname",
    "Battlefield Counterstrike",
    "Bumperdam Cunterslam",
    "Engelbert Humperdinck",
    "Bendable Cummerbund",
    "Bumblebee Federal Tax",
    "Bumpercar crumplezone",
    "Bendoctor Strangebatch",
    "Cucumber Bandersnatch",
    "Butterdish Crumblescone",
    "Beavermint Cumberbunch",
    "Bumblebee Baggageclaim",
    "Benevolent Computerglitch",
    "Bennydick Cuminhersnatch",
    "Bandersnatch Cumberbund",
    "Bumberbimble Cinderblock",
    "Bellicose Yogamat",
    "Bert Pumpkincatch",
    "Banister Dinkleberg",
    "Babyball Snortpants",
    "Burnt Pumpkinpatch",
    "Bellywig Bunkersplat",
    "Battlefield Overwatch",
    "Denibeit Banderstach",
    "Alphabit Crumblygash",
    "Bonkyhort Cutiebrunch",
    "Benicoot Cumbersnoot",
    "Bonkiehort Cutiebrunch",
    "Frumious Bandersnatch",
    "Porkselding Winkertamp",
    "Morgoblitz Hungelzwork",
    "Bendydick Cumandsnap",
    "Candlecork Wrangletrack",
    "Bumpercar Crumplezone",
    "Benediction Cumbercrack",
    "Crackercrib Dormshabmle",
    "Snortselcrum Quartlevand",
    "Bumblebee BaggageClaim",
    "Brambledumb Lumberplum",
    "Boondocksnort Bopplerack",
    "Murpledweet Perrythnatcher",
    "Benidoodle Cumbersnoodle",
    "Coldersquatch Falterscratch",
    "Crumblecake Bandersnatch",
    "Bendthatdick Cucumberbitch",
    "Eggs Benedict Crumplesnatch",
    "Bankruptcy Client",
    "Backto Cumberwell",
    "Ballsack Candlewax",
    "Beandip Bubblecats",
    "Benadril Casablanca",
    "Beelzebub Carrottop",
    "Bartonfink Briarpatch",
    "Angleclink Danglefort",
    "Bedpan Caravantrash",
    "Benadryl Coochierash",
    "Bangladesh Calabash",
    "Banister Cumberbund",
    "Angleflack Banglesack",
    "Angledort Crumpetgort",
    "Angletrack Rumblebutt",
    "Bendidly Cucumberbutt",
    "Batchmix Cummerbund",
    "Battlefield Counterstrike",
    "Banderclack Tumblebutt",
    "Appleslick Lightedmatch",
    "Amblethwack Ranklebum",
    "Baconcrack Caramelsack",
    "Beaniebaby Cabbagepatch",
    "Amblescum Boondockbum",
    "Banderport Wrangleswatch",
    "Bandersnoot Cummerbund",
    "Banderquack Rumblecatch",
    "Bandaidick Cucumberpatch",
    "Banderbatch Crumpetpatch",
    "Banderscratch Mangleshack",
    "Bendickerbong",
    "Bendable Cucumbe",
    "Beneficial Cucumber",
    "Benedicio Cumbecio",
    "Bentdick Cokesnatch",
    "Bonydick Curlysnatch",
    "Benadryl Coughsyrup",
    "Bockdawock Cullywort",
    "Bonkyhort Cutiebrunch",
    "Bigdicked Buttersnatch",
    "Benedict Cumberbatch",
    "Binkledork Crumsworth",
    "Bendylick Sambercatch",
    "Benefect Cumbercrunch",
    "Bendingo Cumbersome",
    "Benadryl Cumonherback",
    "Bentdick Cucumberpatch",
    "Boodlydoopfloofernoodle",
    "Bengay Chocolatefactory",
    "Bendydick Crumplesnatch",
    "Benelick Cucumbersnatch",
    "Bendy-dick Clumsysnatch",
    "Blunderdict Cabbagepatch",
    "Benedictus Bayernquatsch",
    "Bendystraw Caggagepatch",
    "Blender Mccucumberpatch",
    "Bobblespork Wanglesnatch",
    "Blenderdick Pumpmysnatch",
    "Benzenedick Clockworkshop",
    "Bendabledick Cranberrysnatch",
    "Bulbasaur Cucumber",
    "Brandonburg FlipFlop",
    "Butterbean Cobblepot",
    "Brandybuck candycane",
    "Broccoli Cabbagepatch",
    "Bubmlesack Cucumber",
    "Bumbleplink Jangledort",
    "Bumblewort Jangleface",
    "Bumblebee Crackerjack",
    "Breadworm Cinklestoop",
    "Bouillabase Chardonnay",
    "Bourgeoise Catastrophe",
    "Burgerking Cucuflerpark",
    "Bumblekink Humblesack",
    "Burnedick Cumdumpster",
    "Bundledip Cabbagewank",
    "Bopplequart Dinglesnack",
    "Bramblebutt Humblemink",
    "Boppleplink Boppleface",
    "Brunklesport Crumpetfork",
    "Bubblebutt Thundersnatch",
    "Briefcaseboy Caravanclub",
    "Bubblegum Candywrapper",
    "Brambleslum Spanglesport",
    "Bramblecatch Camelmatch",
    "Bumblebee Cucumberfudge",
    "Boondocktack Manglecrumb",
    "Boondocklatch Crumpetshack",
    "Boondocksnort Fumblemort",
    "Bumbletumble Humblecrumble",
    "Beeneedeenee Cumberbumber"
] 

browser.storage.local.get('beeneedeenee.cumberbumber.settings')
    .then(item => {
        if (item['beeneedeenee.cumberbumber.settings'].active) {
            for (elemType of ['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'title']){
                for (elem of document.getElementsByTagName(elemType)) {
                    elem.textContent = elem.textContent.replace(/benedict cumberbatch/gi,names[Math.floor(Math.random() * names.length)]);
                }    
            }
        }
    })